name: backend

on:
  push:
    branches:
      - main
      - release
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
      - release
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  analysis:
    runs-on: ubuntu-latest
    env:
      SONARQUBE_PROJECT_KEY: F12-local
      SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
      SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_BRANCH: ${{ github.event.pull_request.branch }}
    outputs:
      matrix: ${{ steps.parse_json_data.outputs.matrix }}
    steps:
      - name: checkout source code
        uses: actions/checkout@v2

      - name: get analysis results
        id: get_analysis_results
        run: |
          curl --request GET \
          --header 'Authorization:Basic ${{ env.SONARQUBE_TOKEN }}' \
          --url ${{ env.SONARQUBE_URL }}/api/measures/search?projectKeys=${{ env.SONARQUBE_PROJECT_KEY }}&metricKeys=bugs,vulnerabilities,security_hotspots,code_smells,coverage,tests,test_success_density,test_failures,test_errors,skipped_tests,duplicated_lines_density,duplicated_files,duplicated_blocks
      - name: parse json data
        id: parse_json_data
        run: |
          echo "::set-output name=matrix::${{ fromJson(steps.get_analysis_results.outputs.measures.matrix) }}"
  comment:
    needs: analysis
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ needs.analysis.outputs.matrix }}
    steps:
      - name: parse json data2
        if: ${{ matrix.metric }} == 'code_smells'
        run: echo "code_smells_value=${{ matrix.value }}" >> $GITHUB_ENV

      - name: comment Sonarqube URL
        uses: actions/github-script@v4
        with:
          script: |
            const { SONARQUBE_PROJECT_KEY, SONARQUBE_URL, PR_NUMBER } = process.env
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## π§ Analysis Results
            ${ env.code_smells_value }
            ${ SONARQUBE_PROJECT_KEY }-${ PR_NUMBER }
            [λ¶„μ„ κ²°κ³Ό ν™•μΈν•κΈ°](${SONARQUBE_URL})`
            })
